# Generated by Django 5.1.1 on 2024-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Self-Care', max_length=100),
        ),
    ]
