# Generated by Django 5.1.1 on 2024-09-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_doctorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctors/'),
        ),
    ]
