# Generated by Django 5.1.1 on 2024-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_doctorinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='specialist',
            field=models.CharField(default='Psychiatric', max_length=20),
        ),
    ]
